# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    import _cutelib
else:
    import _cutelib

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def cute_correlation_scaled(ngal, pos, nside, fld, msk, thmin, thmax, nth, do_log, hf_th, hm_th):
    return _cutelib.cute_correlation_scaled(ngal, pos, nside, fld, msk, thmin, thmax, nth, do_log, hf_th, hm_th)

def cute_correlation_scaled_2D(ngal, pos, nside, fld, msk, thmin, thmax, nth, na, do_log, hf_th, hm_th):
    return _cutelib.cute_correlation_scaled_2D(ngal, pos, nside, fld, msk, thmin, thmax, nth, na, do_log, hf_th, hm_th)

def cute_line_correlation(nside, fld, msk, xmin, xmax, nx, do_log, hf_th, hm_th, per_bin):
    return _cutelib.cute_line_correlation(nside, fld, msk, xmin, xmax, nx, do_log, hf_th, hm_th, per_bin)

def cute_correlation_wrap(npos, npix, npix2, thmax, nth, nside, dout):
    return _cutelib.cute_correlation_wrap(npos, npix, npix2, thmax, nth, nside, dout)

def cute_correlation_2D_wrap(npos, npix, npix2, thmax, nth, na, nside, dout):
    return _cutelib.cute_correlation_2D_wrap(npos, npix, npix2, thmax, nth, na, nside, dout)

def cute_line_correlation_wrap(npixs, npix2, thmax, nth, nside, per_bin, dout):
    return _cutelib.cute_line_correlation_wrap(npixs, npix2, thmax, nth, nside, per_bin, dout)


